app/app/urls.py
from django.conf.urls import include, url
from django.urls import path

urlpatterns = [
    url(r'^', include(('authentication.urls', 'authentication'), namespace='authentication')),
    url(r'^', include(('user_manager.urls', 'user_manager'), namespace='user_manager')),
]

app/authentication/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^login$', views.login, name="login"),
    url(r'^register/$', views.register, name="register"),
]

app/user_manager/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^user/(?P<user_id>[0-9]+)$', views.update_user, name='user'),
]

app/authentication/models.py
from django.db import models

class User(models.Model):
    email = models.EmailField(max_length=200, unique=True)
    password = models.CharField(max_length=200)

app/user_manager/forms.py
from django import forms

from authentication.models import User

class EditUserForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ['email']
		widgets = {
			'email': forms.EmailInput(
				attrs = {
					'class': 'form-control',
					'id': 'new-email',
					'placeholder': 'E-mail'
				})
		}

app/authentication/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.shortcuts import redirect

from .models import User

def home(request):
	return HttpResponseRedirect('/login')

def login(request):
	context = {}
	if (request.POST):
		try:
			user = get_object_or_404(User, email=request.POST['email'], password=request.POST['password'])
			return HttpResponseRedirect(reverse('user_manager:user', args=(user.id,)))
		except:
			context['error_message'] = 'E-mail ou mot de passe erroné'

	return HttpResponse(render(request, 'login/index.html', context))

def register(request):
	context = {}
	if (request.POST):
		try:
			user = User(email=request.POST['email'], password=request.POST['password'])
			user.save()
			return HttpResponseRedirect(reverse('authentication:login'))
		except:
			context['error_message'] = 'Un compte avec cette address e-mail est déjà existant'

	return HttpResponse(render(request, 'register/index.html', context))

app/user_manager/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse

from authentication.models import User
from .forms import EditUserForm
import json

def update_user(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    context = {
        'user': user
    }
    if (request.POST):
        form = EditUserForm(request.POST, instance=user)
        response_data = {}
        if form.is_valid():
            user = form.save()
            response_data['result'] = 'SUCCESS'
            response_data['email'] = user.email
        else:
            response_data['error_message'] = 'Cette addresse e-mail est déjà associée à un compte ou est invalide'

        return HttpResponse(
            json.dumps(response_data),
            content_type="application/json"
        )
    else:
        form = EditUserForm(instance=user)
    context['form'] = form
    return HttpResponse(render(request, 'user/index.html', context))

app/authentication/templates/login/index.html
{% extends "base.html" %}

{% block content %}
<div class="container">

    <div class="panel panel-primary">
        <div class="panel-heading">
            <h1>Connexion</h1>
        </div>
        <div class="panel-body">

        <form action="{% url 'authentication:login' %}" id="login-form" method="post">
            {% csrf_token %}

            <div class="input-group">
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                </span>
                <input class="form-control" type="email" id="email" name="email" required placeholder="E-mail">
            </div>

            <div class="input-group">
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-lock" aria-hidden="true"></span>
                </span>
                <input class="form-control" type="password" id="password" name="password" required placeholder="Mot de passe">
            </div>

        </form>
        {% if error_message %}<p id="error-message"><strong>{{ error_message }}</strong></p>{% endif %}
        <div class="centered">
            <button type="submit" form="login-form" value="Submit" class="btn btn-primary">Se connecter</button>
        </div>
    </div>
    <div class="panel-footer">
        <p>Pas encore de compte? <a href="{% url 'authentication:register'%}">Inscrivez-vous dès maintenant!</a></p>
    </div>
    </div>
</div>
{% endblock %}

app/authentication/templates/register/index.html
{% extends "base.html" %}

{% block content %}
<div class="container">

    <div class="panel panel-primary">
        <div class="panel-heading">
            <h1>Inscription</h1>
        </div>
        <div class="panel-body">

        <form action="{% url 'authentication:register' %}" id="register-form" method="post">
            {% csrf_token %}

            <div class="input-group">
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                </span>
                <input class="form-control" type="email" id="email" name="email" required placeholder="E-mail">
            </div>

            <div class="input-group">
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-lock" aria-hidden="true"></span>
                </span>
                <input class="form-control" type="password" id="password" name="password" required placeholder="Mot de passe">
            </div>

        </form>
        {% if error_message %}<p id="error-message" class="centered"><strong>{{ error_message }}</strong></p>{% endif %}
        <div class="centered">
            <button type="submit" form="register-form" value="Submit" class="btn btn-primary">S'inscrire</button>
        </div>
    </div>
    <div class="panel-footer">
        <p>Déjà un compte? <a href="{% url 'authentication:login'%}">Connectez-vous!</a></p>
    </div>
    </div>
</div>
{% endblock %}

app/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- jQuery  -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>

    <!-- jQuery Modal -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Custom Stripe Styling -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% block base_head %}{% endblock %}
  </head>
  <body>

    {% block content %}{% endblock %}

    {% block javascript %}{% endblock %}

  </body>
</html>

app/templates/login/index.html
{% extends "base.html" %}

{% block content %}
<div class="container">

    <div class="panel panel-primary">
        <div class="panel-heading">
            <h1>Connexion</h1>
        </div>
        <div class="panel-body">

        <form action="{% url 'authentication:login' %}" id="login-form" method="post">
            {% csrf_token %}

            <div class="input-group">
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                </span>
                <input class="form-control" type="email" id="email" name="email" required placeholder="E-mail">
            </div>

            <div class="input-group">
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-lock" aria-hidden="true"></span>
                </span>
                <input class="form-control" type="password" id="password" name="password" required placeholder="Mot de passe">
            </div>

        </form>
        {% if error_message %}
            <div class='alert-danger alert radius' id="error-message">
                <p><strong>{{ error_message }}</strong></p>
            </div>
        {% endif %}
        <div class="centered">
            <button type="submit" form="login-form" value="Submit" class="btn btn-primary">Se connecter</button>
        </div>
    </div>
    <div class="panel-footer">
        <p>Pas encore de compte? <a href="{% url 'authentication:register'%}">Inscrivez-vous dès maintenant!</a></p>
    </div>
    </div>
</div>
{% endblock %}

app/templates/register/index.html
{% extends "base.html" %}

{% block content %}
<div class="container">

    <div class="panel panel-primary">
        <div class="panel-heading">
            <h1>Inscription</h1>
        </div>
        <div class="panel-body">

        <form action="{% url 'authentication:register' %}" id="register-form" method="post">
            {% csrf_token %}

            <div class="input-group">
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                </span>
                <input class="form-control" type="email" id="email" name="email" required placeholder="E-mail">
            </div>

            <div class="input-group">
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-lock" aria-hidden="true"></span>
                </span>
                <input class="form-control" type="password" id="password" name="password" required placeholder="Mot de passe">
            </div>

        </form>
        {% if error_message %}
            <div class='alert-danger alert radius' id="error-message">
                <p><strong>{{ error_message }}</strong></p>
            </div>
        {% endif %}
        <div class="centered">
            <button type="submit" form="register-form" value="Submit" class="btn btn-primary">S'inscrire</button>
        </div>
    </div>
    <div class="panel-footer">
        <p>Déjà un compte? <a href="{% url 'authentication:login'%}">Connectez-vous!</a></p>
    </div>
    </div>
</div>
{% endblock %}

app/templates/user/index.html
{% extends "base.html" %}
{% load static %}

{% block base_head %}
<link rel="stylesheet" href="{% static 'css/user.css' %}">
{% endblock %}

{% block javascript %}
<script src="{% static 'js/user.js' %}"></script>
{% endblock %}

{% block content %}

<div id="user-page" class="container">

  <!-- Modal -->
  <div id="update-email-modal" class="modal">
    <form id="change-email-form" data-id={{ user.pk }} method="POST" class="form">
      {% csrf_token %}
      <h3>Veuillez rentrer votre nouvelle email</h3>
      <br>
      <div class="input-group">
        <span class="input-group-addon">
          <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
        </span>
        {{ form.email }}
      </div>
    </form>
    <div id="error-message"></div>
    <div class="centered">
      <button href="#" rel="modal:close" type="submit" form="change-email-form" value="Submit" class="btn btn-primary">Valider</button>
    </div>
  </div>

  <!-- Page content -->
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h1>Bienvenue!</h1>
    </div>
    <div class="panel-body">
      <h2>Informations du compte:</h2>
      <p>
        e-mail: <span id="user-email">{{ user.email }}</span>
        <a  href="#update-email-modal" rel="modal:open">
          <button id="edit-icon" type="button" class="btn btn-default btn-lg">
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
          </button>
        </a>
      </p>
    </div>
  </div>

</div>
{% endblock %}

app/user_manager/templates/user/index.html
{% extends "base.html" %}
{% load static %}

{% block base_head %}
<link rel="stylesheet" href="{% static 'css/user.css' %}">
{% endblock %}

{% block content %}

<div id="user-page" class="container">

  <!-- Modal -->
  <div id="update-email-modal" class="modal">
    <form action="{% url 'user_manager:user' user.pk%}" id="change-email-form" method="POST" class="form">
      {% csrf_token %}
      <h3>Veuillez rentrer votre nouvelle email</h3>
      <br>
      <div class="input-group">
        <span class="input-group-addon">
          <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
        </span>
        {{ form.email }}
      </div>
    </form>
    {% if error_message %}<p id="error-message" class="centered"><strong>{{ error_message }}</strong></p>{% endif %}
    <div class="centered">
      <button href="#" rel="modal:close" type="submit" form="change-email-form" value="Submit" class="btn btn-primary">Valider</button>
    </div>
  </div>

  <!-- Page content -->
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h1>Bienvenue!</h1>
    </div>
    <div class="panel-body">
      <h2>Informations du compte:</h2>
      <p>
        e-mail: {{ user.email }}
        <a  href="#update-email-modal" rel="modal:open">
          <button id="edit-icon" type="button" class="btn btn-default btn-lg">
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
          </button>
        </a>
      </p>
    </div>
  </div>

</div>
{% endblock %}